stages:
  - build
  - tests
  - deploy

Dependencies:
  stage: build
  image: node:17
  script: npm i
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull-push

Lint:
  stage: tests
  image: node:17
  script: npm run lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

Test:
  stage: tests
  image: node:17
  script: npm test
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  only:
    - test
  except:
    - branches
  when: manual

Deploy:
  stage: deploy
  image: node:17
  variables:
    SURGE_LOGIN: ${SURGE_LOGIN}
    SURGE_TOKEN: ${SURGE_TOKEN}
  before_script:
    - npm install --global surge
    - npm build
  script:
    - surge --project ./build --domain ${CNAME}
  after_script:
    - npm uninstall --global surge
    - rm -rf build/
  only:
    - tags
    - /^v-.*$/
  when: manual
